# This is a basic workflow to help you get started with Actions

name: CI TEST

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "Hadeer" branch
  push:
    branches: [ "Hadeer" ]
  pull_request:
    branches: [ "Hadeer" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=15,name=iPhone 12']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@Hadeer
      - name: Build
        run: |
          xcodebuild clean build -project YazeedFitness.xcodeproj -scheme YazeedFitness -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
      - name: Test
        run: |
          xcodebuild clean test -project YazeedFitness.xcodeproj -scheme YazeedFitnessTests -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
